sudo: required

services:
  - docker

script:
- hack/travis_wait_log/travis_wait_log make build

after_success:
- docker images --digests

deploy:
  provider: script
  script: make push
  on:
    branch: master
